In [2]:
import numpy as np

In [16]:
#is there a subset whose sum=sums 
arr=[1,5,5,11,6,7]
sums=15
def isSubsetSum(arr,n,sums):
    if sums == 0:
        return True
    if n==0 and sum!=0:
        return False
    if arr[n-1]>sums:
        return isSubsetSum(arr,n-1,sums)
    return isSubsetSum(arr,n-1,sums) or isSubsetSum(arr,n-1,sums-arr[n-1])
isSubsetSum(arr,len(arr),sums)

False

In [21]:
#fibonaci dp
lookup=[None]*101
n=11
def fib(n,lookup):
    if n==0 or n==1:
        lookup[n]=n
    elif lookup[n]==None:
        lookup[n]=fib(n-1,lookup)+fib(n-2,lookup)
    return lookup[n]
fib(n,lookup)

   

89

In [28]:
#lis recursive
#arr=[10,22,9,33,21,50,41,60,80]
#arr=[3,10,2,1,20]
#arr=[3,2]
arr=[50, 3, 10, 7, 40, 80]
n=len(arr)
def lis(arr,n):
    if n==1:
        return 1
    elif arr[n-1]<arr[n-2]:
        return lis(arr,n-1)
    else:
        return max(lis(arr,n-1)+1,lis(arr,n-1))
lis(arr,n)

4

In [31]:
#lis dp
def lis1(arr):
    n=len(arr)
    dp=[1]*n
    for i in range(1,n):
        for j in range(0,i):
            if arr[i]>arr[j] and dp[i]<dp[j]+1:
                dp[i]=dp[j]+1
    return max(dp)                       

In [35]:
arr=[10,22,9,33,21,50,41,60,80]

lis1(arr)

6

In [103]:
#recursive longest common subsequence
X="AGGTAB"
Y="GXTXAYB"
m=len(X)
n=len(Y)
def lcs(X,Y,m,n):
    if m==0 or n==0:
        return 0
    elif X[m-1]==Y[n-1]:
        return 1+lcs(X,Y,m-1,n-1)
    else:
        return max(lcs(X,Y,m-1,n),lcs(X,Y,m,n-1))
lcs(X,Y,m,n)
    

4

In [57]:
#memoisation lcs
def lcs1(X,Y):
    m=len(X)
    n=len(Y)
    dp=np.zeros([m+1,n+1])
    for i in range(1,m+1):
        for j in range(1,n+1):
            if i==0 or j==0:
                dp[i][j]=0
            elif X[i-1]==Y[j-1]:
                dp[i][j]=1+dp[i-1][j-1]
            else:
                dp[i][j]=max(dp[i-1][j],dp[i][j-1])
    print(dp)
    return np.amax(dp)

X="GAGGTAB"
Y="GXTXAYB"
lcs1(X,Y)            

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 2. 2. 2.]
 [0. 1. 1. 1. 1. 2. 2. 2.]
 [0. 1. 1. 1. 1. 2. 2. 2.]
 [0. 1. 1. 2. 2. 2. 2. 2.]
 [0. 1. 1. 2. 2. 3. 3. 3.]
 [0. 1. 1. 2. 2. 3. 3. 4.]]


4.0

In [63]:
#coin change problem
#in how many ways can we make the change
coins=[2,5,3,6]
sum_c=10
n=len(coins)
def coin_change(coins,sum_c,n):
    if sum_c==0:
        return 1
    if n==0:
        return 0
    if coins[n-1]>sum_c:
        return coin_change(coins,sum_c,n-1)
    else:
        return coin_change(coins,sum_c,n-1)+coin_change(coins,sum_c-coins[n-1],n)
coin_change(coins,sum_c,n)

5

In [78]:
#coin change problem
#minimum no of coin changes required to get required sum 
coins=[1,5,6,8]
sum_c=11
n=len(coins)
def coin_change(coins,sum_c,n):
    if sum_c==0:
        return 0
    if n<=0:
        return 1000
    if coins[n-1]>sum_c:
        return coin_change(coins,sum_c,n-1)
    else:
        return min(coin_change(coins,sum_c,n-1),1+coin_change(coins,sum_c-coins[n-1],n))
coin_change(coins,sum_c,n)

2

In [104]:
#coin change problem
#minimum no of coin changes required to get required sum 
coins=[1,5,6,8]
sum_c=11
n=len(coins)
def coin_change_dp(coins,sum_c):
    dp=np.zeros([len(coins),sum_c+1])
    for i in range(len(coins)):
        for j in range(sum_c+1):
            if j>=coins[i]:
                dp[i][j]=min(dp[i-1][j],dp[i][j-coins[i]]+1)
            else:
                dp[i][j]=dp[i-1][j]
    print(dp,np.amin(dp))
coin_change_dp(coins,sum_c)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 0.0


In [96]:
num=64
def isPower(num):
    return (num &(num-1)==0)
isPower(num)

True

In [108]:
#max product of rod cuts
def rope_cut(n):
    if n==1:
        return 1
    max_val=0
    for i in range(1,n+1):
        value=max(i*(n-i),i*rope_cut(n-i))
        max_val=max(value,max_val)
    return max_val
rope_cut(10)

36

In [117]:
def rope_cut_dp(n):
    a=np.zeros(n+1)
    max_val=0
    for i in range(1,n+1):
        a[i]=max(i*(n-i),i*a[n-i])
    return a    
rope_cut_dp(10)

array([  0.,   9.,  16.,  21.,  24.,  25., 144., 147., 128.,  81.,   0.])

In [3]:
#maximize prize of rod cut
cost=[1,5,8,9,10,17,17,20]
def rope_max_cost(n,cost):
#     if len(cost)!=n:
#         return 0
    if n==0:
        return 0
    max_val=0
    for i in range(1,n+1):
        value=max(cost[i-1]+cost[n-i-1],cost[i-1]+rope_max_cost([n-i-1],cost))
        max_val=max(value,max_val)
        print(max_val,i)
    return max_val
rope_max_cost(8,cost)

TypeError: can only concatenate list (not "int") to list

In [124]:
import sys
-sys.maxsize-1

-9223372036854775808

In [1]:
9^5

12

In [3]:
arr=[9,3,5]
def min_xor(arr):
    arr.sort()
    value=100
    print(arr)
    for i in range(len(arr)-1):
        value=min(value,arr[i]^arr[i+1])
    return value
min_xor(arr)

[3, 5, 9]


6

In [30]:
solve

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
#maze=[[0,0,0],[9,1,1],[0,1,0]]
maze=[[1,0,0,0],[1,1,0,1],[0,1,0,0],[1,1,1,9]]
print(np.array(maze))
n=len(maze)
solve=np.zeros([n,n])
def issafe(maze,x,y,n):
    if x>=0 and x<n and y>=0 and y<n and maze[x][y]==1:
        return True
    else:
        return False
def rat_maze(maze,x,y,n,solve):
#     if(maze[x][y]!=1):
#         return False
    if x<n and y<n and maze[x][y]==9:
        solve[x][y]=1
        return True
    if issafe(maze,x,y,n):
        solve[x][y]=1
        if rat_maze(maze,x+1,y,n,solve):
            return True
        if rat_maze(maze,x,y+1,n,solve):
            return True
        solve[x][y]=0
        return False
print(rat_maze(maze,0,0,n,solve))
print(solve)

[[1 0 0 0]
 [1 1 0 1]
 [0 1 0 0]
 [1 1 1 9]]
True
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 1. 1.]]


In [1]:
#count no of paths to maze
maze=[[0,0,0,0],[0,-1,0,1],[0,1,0,0],[1,1,1,9]]
print(np.array(maze))
n=len(maze)
solve=np.zeros([n,n])
def issafe(maze,x,y,n):
    if x>=0 and x<n and y>=0 and y<n and maze[x][y]==1:
        return True
    else:
        return False
def rat_maze(maze,x,y,n,solve):
#     if(maze[x][y]!=1):
#         return False
    if x<n and y<n and maze[x][y]==9:
        solve[x][y]=1
        return True
    if issafe(maze,x,y,n):
        solve[x][y]=1
        if rat_maze(maze,x+1,y,n,solve):
            return True
        if rat_maze(maze,x,y+1,n,solve):
            return True
        solve[x][y]=0
        return False
print(rat_maze(maze,0,0,n,solve))
print(solve)

NameError: name 'np' is not defined

In [40]:
txt = "ABABDABACDABABCABAB"
pat = "ABABCABAB"
m=len(pat)
lps=[0]*m
lps[0]=0
for i in range(1,m):
    if pat[i]==:
        
    

In [39]:
lps

[0, 0, 0, 0, 0, 0, 0, 0, 0]

In [41]:
pat

'ABABCABAB'

In [42]:
pat.remove[0]

AttributeError: 'str' object has no attribute 'remove'

In [45]:
lst = [['gfg is'], ['a portal'], ['for geeks']] 
lst.sort()
lst

[['a portal'], ['for geeks'], ['gfg is']]

In [46]:
lst=[[u'g1', u'act', u'car'], [u'ab1', u'off', u'key', u'dog'], [u'a8', u'act', u'zoo']]
lst.sort()
lst

[['a8', 'act', 'zoo'], ['ab1', 'off', 'key', 'dog'], ['g1', 'act', 'car']]

In [48]:
def Punctuation(string): 
  
    # punctuation marks 
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
  
    # traverse the given string and if any punctuation 
    # marks occur replace it with null 
    for x in string.lower(): 
        print(x)
        if x in punctuations: 
            string = string.replace(x, "") 
  
    # Print string without punctuation 
    print(string) 
  
# Driver program 
string = "Welcome???@@##$ to#$% Geeks%$^for$%^&Geeks"
Punctuation(string)


w
e
l
c
o
m
e
?
?
?
@
@
#
#
$
 
t
o
#
$
%
 
g
e
e
k
s
%
$
^
f
o
r
$
%
^
&
g
e
e
k
s
Welcome to GeeksforGeeks


In [61]:
int(not(0^1))

0

In [64]:
int(not(1^0))

0

In [65]:
cells=[0,1,0,1,1,0,0,1]

In [74]:
cells

[0, 1, 0, 1, 1, 0, 0, 1]

In [73]:
new

[0, 1, 0, 1, 1, 0, 0, 1]

In [72]:
cells=[0,1,0,1,1,0,0,1]
new=list(cells)

In [75]:
for j in range(len(cells)):
    if j==0:
        new[j]=int(not(cells[j+1]^0))
        print(new,cells)
    elif j==len(cells)-1:
        new[j]=int(not(cells[j-1]^0))
        print(new,cells)
    else:
        print(j,cells[j-1],cells[j+1])
        print(new,cells)
        new[j]=int(not(cells[j-1]^cells[j+1]))
print(new)



[0, 1, 0, 1, 1, 0, 0, 1] [0, 1, 0, 1, 1, 0, 0, 1]
1 0 0
[0, 1, 0, 1, 1, 0, 0, 1] [0, 1, 0, 1, 1, 0, 0, 1]
2 1 1
[0, 1, 0, 1, 1, 0, 0, 1] [0, 1, 0, 1, 1, 0, 0, 1]
3 0 1
[0, 1, 1, 1, 1, 0, 0, 1] [0, 1, 0, 1, 1, 0, 0, 1]
4 1 0
[0, 1, 1, 0, 1, 0, 0, 1] [0, 1, 0, 1, 1, 0, 0, 1]
5 1 0
[0, 1, 1, 0, 0, 0, 0, 1] [0, 1, 0, 1, 1, 0, 0, 1]
6 0 1
[0, 1, 1, 0, 0, 0, 0, 1] [0, 1, 0, 1, 1, 0, 0, 1]
[0, 1, 1, 0, 0, 0, 0, 1] [0, 1, 0, 1, 1, 0, 0, 1]
[0, 1, 1, 0, 0, 0, 0, 1]


In [82]:
points=[[1,3],[-2,2]]
dist={}
for i in range(len(points)):
    dist[i]=points[i][0]**2+points[i][1]**2
print(dist)

{0: 10, 1: 8}


In [83]:
for i in sorted(dist.keys()):
    print(i)

0
1


In [84]:
for i in sorted(dist.items(),key=lambda kv:(kv[i],kv[0])):
    print(i)
    

(1, 8)
(0, 10)


In [100]:
print(points)
points.sort(key =lambda P:P[0]**2+P[1]**2)
print(points[:3])

[[1, 3], [-2, 2], [1, 2], [0, 3], [1, 0]]
[[1, 0], [1, 2], [-2, 2]]


In [108]:
points=[[1,3],[-2,2],[1,2],[0,3],[1,0]]
points.sort(key=lambda P:P[1])
points

[[1, 0], [-2, 2], [1, 2], [1, 3], [0, 3]]

In [101]:
60%36

24

In [102]:
36%24

12

In [29]:
subsequent_strings=set()
def subsequent(s):
    if len(s)==1:
        return s
    else:
        for i in range(1,len(s)):
            subsequent_strings.add(s)
            s1=subsequent(s[:-i])
            s2=subsequent(s[i:])
            subsequent_strings.add(s1)
            subsequent_strings.add(s2)
subsequent("12322")
print(subsequent_strings)
print(count(subsequent_strings))



{'32', '322', '12', '12322', '2', '1', '23', '3', '1232', '2322', '22', None, '232', '123'}


NameError: name 'count' is not defined

In [40]:
print(subsequent_strings)
# subsequent_strings.remove(None)
for i in subsequent_strings:
    print(unique(i))
# print(sorted(subsequent_strings,key=unique(k)))
# print(len(subsequent_strings))

{'32', '322', '12', '12322', '2', '1', '23', '3', '1232', '2322', '22', '232', '123'}


NameError: name 'unique' is not defined

In [41]:
unique(1231)

NameError: name 'unique' is not defined

In [26]:
from itertools import permutations
def allpermutations(a):
    permlist=permutations(a)
    perms=set()
    for perm in list(permlist):
        s1=''.join(perm)
#         print(s1)
        perms.add(s1)
    print(perms)
def permute(a,l,r):
    if l==r:
        print(''.join(a))
    else:
        for i in range(l,r+1):
            a[l],a[i]=a[i],a[l]
            permute(a,l+1,r)
            a[l],a[i]=a[i],a[l]
# allpermutations("AABC")
permute(list("ABC"),0,len("ABC")-1)

ABC
ACB
BAC
BCA
CBA
CAB


In [48]:
def palindrome(a):
    n=len(a)
    for i in range(0,int(n/2)):
        if a[i]!=a[n-i-1]:
            return False
    return True
palindrome("aba")

True

In [13]:
str1="abcdeabcd"
res=0
for i in str1:
    res=res^ord(i)
chr(res)

'e'

In [6]:
ord("c")

99

In [7]:
ord('a')^ord('a')^ord('b')^ord('b')

0

In [17]:
def count_set_bits(n):
    count=0
    while(n):
        print(count,n)
        count+=(n&1)
        n>>=1
    return count
count_set_bits(7)

0 7
1 3
2 1


3

In [54]:
s="Mr   Smith Ahuja   "
words=s.split()
s='%20'.join(words)
print(s)
# length=14
# flag=0
# for i in range(len(s)-1,-1,-1):
#     print(s[i])
#     if s[i]!=" ":
#         flag=0
#     elif s[i]==" " and flag==0:
#         flag=1
#         s.replace(s[i],"%20")
#     else:
#         s.replace(s[i],"")
# #     print(new_s)
# print(s)
        
        

Mr%20Smith%20Ahuja


In [66]:
s1="paile"
s2="aale"
j=len(s2)-1
count=0
for i in range(len(s1)-1,-1,-1):
    print(s1[i])
    if s1[i]!=s2[j]:
        count+=1
    else:
        j-=1
if count==1:
    print("yes")
else:
    print("no")

e
l
i
a
p
no


In [72]:
a="aabccccdddaaa"
count=1
a1=""
char=a[0]
for i in range(1,len(a)):
    if char==a[i]:
        count+=1
    else:
        a1=a1+char+str(count)
        count=1
        char=a[i]
a1=a1+char+str(count)
print(a1)
    

a2b1c4d3a3


In [1]:
10^9

3

In [2]:
10**9

1000000000